# Generated by Django 3.2.6 on 2022-04-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='default_book.jpg', upload_to='book_images')),
            ],
        ),
    ]
